### ISSUE TITLE
Utilisation de Git

### ISSUE THREAD

**Issue by drazik** [julienpa/web-project#2]
Dans les critères d'évaluation, actuellement il est précisé : 

> Utilisation de git : organisation du repository et des branches, utilisations de PR/MR, fréquence et cohérence des commits

Est-ce qu'on garde ça ? Ce serait peut-être pas mal de le mettre en bonus non ? Il me semble que les étudiants n'ont pas spécialement reçu de formation sur Git.

**Comment by julienpa** [comment]
@drazik Alexandre a fait une mini formation Git hier (mardi), donc ça paraît intéressant de le garder mais je ne suis pas contre le mettre en bonus :)
cc @seafoox

**Comment by drazik** [comment]
OK on peut le garder alors
